### ISSUE TITLE
Keeps searching

### ISSUE THREAD

**Issue by ferbas** [ex0nuss/Plex-Export-Docker#1]
Hi,

It keeps searching even i choose for only for one section . What do i wrong?

 sudo docker-compose up
/usr/local/lib/python2.7/dist-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
Recreating plexexport-php ... 
Recreating plexexport-php ... done
Recreating plexexport-nginx ... 
Recreating plexexport-nginx ... done
Attaching to plexexport-php, plexexport-nginx
plexexport-php      | Sleeps for 15s to initialize
plexexport-nginx    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
plexexport-nginx    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
plexexport-nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
plexexport-nginx    | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
plexexport-nginx    | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
plexexport-nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
plexexport-nginx    | /docker-entrypoint.sh: Configuration complete; ready for start up
plexexport-php      | 03:59:35 Welcome to the Plex Exporter v1
plexexport-php      | 03:59:35 Searching for sections in the Plex library at http://plex.ferhatbaskale.com:32400/

version: '3'

services:
  plexexport-php:
    image: ex0nuss/plex-export-docker:latest
    container_name: plexexport-php
    restart: unless-stopped
    volumes:
      - ./data-plexexport:/data
    environment:
      - PLEX_URL=http://plex.ferhatbaskale.com:32400
      - PLEX_TOKEN=XXXXXXXXXXXXXXXXXXX
      - PLEX_SECTIONS=Movies Korean

  plexexport-nginx:
    image: nginx:latest
    container_name: plexexport-nginx
    restart: unless-stopped
    ports:
      - 8888:80
    volumes:
      - ./data-plexexport:/data
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - plexexport-php

**Comment by ex0nuss** [comment]
Hi,

thx for contacting me. 
First of all, I removed your PLEX_TOKEN form your Issue. It's not reccomenden to post this token publicly for security reasons :)

It seems like that the PHP-Container (plexexport-php) can not connect to your Plex-Server. This can have multi

**Comment by ex0nuss** [comment]
Hi,

thx for contacting me.
First of all, I removed your PLEX_TOKEN form your Issue. It's not recommended to post this token publicly due to security reasons :)

It seems like that the PHP-Container (plexexport-php) can not connect to your Plex-Server. 
This can have multiple reasons: 
- Your Plex-Server is not reachable (e.g. Due to wrong configuration or network issues)
- Your Plex-Server is down
- Your Plex_TOKEN is not correct

### First step
I would recommend to check if your **PLEX_TOKEN is correct** and the **entire TOKEN is inside the docker-compose.yml**

### Second step
To make troubleshooting easier please **remove the "PLEX_SECTIONS" environment variable**. After we figured out your problem you can add it back in. 
Now please test if it works.

### Third step
Please try **removing the port (:32400) from your PLEX_URL env var**. 
It seems like that you are running a reverse proxy using port 80 with a redirect to 443. 
```
environment:
  - PLEX_URL=http://plex.ferhatbaskale.com
  - PLEX_TOKEN=your_plex_token_goes_here
```
Now please test again if it works.
Please try also it using HTTP**S** in the PLEX_URL
```
environment:
  - PLEX_URL=https://plex.ferhatbaskale.com
  - PLEX_TOKEN=your_plex_token_goes_here
```
Now please test again if it works.

### Fourth step
Since you try accessing your Plex-server via a public domain, please also try also accessing it **via your private IP address** if possible. 
Note: Keep in mind **choosing the right port** when using private IP addresses!
This is how I access my Plex-server:
```
environment:
  - PLEX_URL=http://192.168.1.100:32400
```
Now please test again if it works.


Hopefully this will help fixing your issue.
Please answer if this helped you :)
Regards.

**Comment by ferbas** [comment]
OOOOOOOOOOOH MY GOD
You're my hero  :)

Thx for your explanation and your help.
It seems after i've followed your second step and third step it begins to
see my list.
I have one problem and it is Error: Could not load thumbnail


Do you have a solution for this too?


plexexport-php      | 15:56:14 Welcome to the Plex Exporter v1
plexexport-php      | 15:56:14 Searching for sections in the Plex library
at http://plex.ferhatbaskale.com/
plexexport-php      | 15:56:14 Found 10 sections in this Plex library
plexexport-php      | 15:56:14 Scanning section: Anime
plexexport-php      | 15:56:15 Found 227 shows in Anime
plexexport-php      | 15:56:15 Scanning show: 07-Ghost
plexexport-php      | 15:56:17 Error: Could not load thumbnail for 07-Ghost
plexexport-php      | 15:56:18 Scanning show: A.I.C.O. Incarnation

**Comment by ex0nuss** [comment]
Hehe I am glad that you can connect to Plex now :D

Yeah I thought the port (32400) was the problem ^^
**Just as a tipp:** Using the private IP address instead of your domain name might increase the speed.

<br/>
Regarding your thumbnail problem:

- Is this thumbnail loading problem only for "07-Ghost" or for every movie?
- Do the other thumbnails show up on the website?

**Comment by ferbas** [comment]
I have tried with anime and movies also


[image: image.png]

ferbas@plexserver:/plex-export$ sudo docker-compose up
/usr/local/lib/python2.7/dist-packages/cryptography/__init__.py:39:
CryptographyDeprecationWarning: Python 2 is no longer supported by the
Python core team. Support for it is now deprecated in cryptography, and
will be removed in a future release.
  CryptographyDeprecationWarning,
Recreating plexexport-php ...
Recreating plexexport-php ... done
Recreating plexexport-nginx ...
Recreating plexexport-nginx ... done
Attaching to plexexport-php, plexexport-nginx
plexexport-php      | Sleeps for 15s to initialize
plexexport-nginx    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not
empty, will attempt to perform configuration
plexexport-nginx    | /docker-entrypoint.sh: Looking for shell scripts in
/docker-entrypoint.d/
plexexport-nginx    | /docker-entrypoint.sh: Launching
/docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
plexexport-nginx    | 10-listen-on-ipv6-by-default.sh: Getting the checksum
of /etc/nginx/conf.d/default.conf
plexexport-nginx    | 10-listen-on-ipv6-by-default.sh: info:
/etc/nginx/conf.d/default.conf differs from the packaged version
plexexport-nginx    | /docker-entrypoint.sh: Launching
/docker-entrypoint.d/20-envsubst-on-templates.sh
plexexport-nginx    | /docker-entrypoint.sh: Configuration complete; ready
for start up
plexexport-php      | 16:31:10 Welcome to the Plex Exporter v1
plexexport-php      | 16:31:10 Searching for sections in the Plex library
at http://plex.ferhatbaskale.com/
plexexport-php      | 16:31:11 Found 10 sections in this Plex library
plexexport-php      | 16:31:11 Scanning section: Movies Korean
plexexport-php      | 16:31:12 Found 26 movies in Movies Korean
plexexport-php      | 16:31:12 Scanning movie: #Alive
plexexport-php      | 16:31:13 Error: Could not load thumbnail for #Alive
plexexport-php      | 16:31:13 Scanning movie: 3-Iron
plexexport-php      | 16:31:14 Error: Could not load thumbnail for 3-Iron
plexexport-php      | 16:31:15 Scanning movie: Always
plexexport-php      | 16:31:16 Error: Could not load thumbnail for Always
plexexport-php      | 16:31:17 Scanning movie: Barking Dogs Never Bite
plexexport-php      | 16:31:19 Error: Could not load thumbnail for Barking
Dogs Never Bite
plexexport-php      | 16:31:20 Scanning movie: The Beauty Inside
plexexport-php      | 16:31:20 Error: Could not load thumbnail for The
Beauty Inside
plexexport-php      | 16:31:21 Scanning movie: Bounty Hunters
plexexport-php      | 16:31:21 Error: Could not load thumbnail for Bounty
Hunters
plexexport-php      | 16:31:22 Scanning movie: The Call
plexexport-php      | 16:31:24 Error: Could not load thumbnail for The Call
plexexport-php      | 16:31:25 Scanning movie: Extreme Job
plexexport-php      | 16:31:26 Error: Could not load thumbnail for Extreme
Job
plexexport-php      | 16:31:27 Scanning movie: Gangnam Blues
plexexport-php      | 16:31:29 Error: Could not load thumbnail for Gangnam
Blues
plexexport-php      | 16:31:30 Scanning movie: Hit-and-Run Squad
plexexport-php      | 16:31:30 Error: Could not load thumbnail for
Hit-and-Run Squad
plexexport-php      | 16:31:31 Scanning movie: Hot Young Bloods
plexexport-php      | 16:31:32 Error: Could not load thumbnail for Hot
Young Bloods
plexexport-php      | 16:31:33 Scanning movie: Love Forecast
plexexport-php      | 16:31:36 Error: Could not load thumbnail for Love
Forecast
plexexport-php      | 16:31:37 Scanning movie: A Man and a Woman
plexexport-php      | 16:31:38 Error: Could not load thumbnail for A Man
and a Woman
plexexport-php      | 16:31:39 Scanning movie: Miracle in Cell No. 7
plexexport-php      | 16:31:40 Error: Could not load thumbnail for Miracle
in Cell No. 7
plexexport-php      | 16:31:40 Scanning movie: Mulan
plexexport-php      | 16:31:41 Error: Could not load thumbnail for Mulan
plexexport-php      | 16:31:41 Scanning movie: My Love, My Bride
plexexport-php      | 16:31:44 Error: Could not load thumbnail for My Love,
My Bride
plexexport-php      | 16:31:44 Scanning movie: My Sassy Girl
plexexport-php      | 16:31:45 Error: Could not load thumbnail for My Sassy
Girl
plexexport-php      | 16:31:46 Scanning movie: My Wife Is a Gangster
plexexport-php      | 16:31:47 Error: Could not load thumbnail for My Wife
Is a Gangster
plexexport-php      | 16:31:47 Scanning movie: Parasite
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:49 +0000] "GET /
HTTP/1.1" 200 2880 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:49 +0000] "GET
/assets/css/style.css HTTP/1.1" 200 9511 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:49 +0000] "GET
/assets/js/jquery.1.4.4.min.js HTTP/1.1" 200 78600 "
http://192.168.0.123:8888/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:49 +0000] "GET
/assets/js/utils.js HTTP/1.1" 200 1151 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:49 +0000] "GET
/assets/js/plex.js HTTP/1.1" 200 22313 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/css/iphone.css HTTP/1.1" 200 1328 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/css/iphone-retina.css HTTP/1.1" 200 0 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/background.jpg HTTP/1.1" 200 5629 "
http://192.168.0.123:8888/assets/css/style.css" "Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/container-bg.png HTTP/1.1" 200 291 "
http://192.168.0.123:8888/assets/css/style.css" "Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/logo.png HTTP/1.1" 200 19609 "
http://192.168.0.123:8888/assets/css/style.css" "Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/plex-data/data.js HTTP/1.1" 304 0 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/icon-movie.png HTTP/1.1" 200 798 "
http://192.168.0.123:8888/assets/css/style.css" "Mozilla/5.0 (Windows NT
10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/default.png HTTP/1.1" 200 4126 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-nginx    | 192.168.0.234 - - [05/Dec/2020:16:31:50 +0000] "GET
/assets/images/favicon.ico HTTP/1.1" 200 1150 "http://192.168.0.123:8888/"
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like
Gecko) Chrome/87.0.4280.88 Safari/537.36"
plexexport-php      | 16:31:50 Error: Could not load thumbnail for Parasite
plexexport-php      | 16:31:51 Scanning movie: Peninsula
plexexport-php      | 16:31:52 Error: Could not load thumbnail for Peninsula
plexexport-php      | 16:31:53 Scanning movie: Time Renegades
plexexport-php      | 16:31:54 Error: Could not load thumbnail for Time
Renegades
plexexport-php      | 16:31:55 Scanning movie: Train to Busan
plexexport-php      | 16:31:55 Error: Could not load thumbnail for Train to
Busan
plexexport-php      | 16:31:56 Scanning movie: Twenty
plexexport-php      | 16:31:57 Error: Could not load thumbnail for Twenty
plexexport-php      | 16:31:58 Scanning movie: Unforgettable
plexexport-php      | 16:31:59 Error: Could not load thumbnail for
Unforgettable
plexexport-php      | 16:32:00 Scanning movie: Veteran
plexexport-php      | 16:32:01 Error: Could not load thumbnail for Veteran
plexexport-php      | 16:32:01 Scanning movie: The Warrior
plexexport-php      | 16:32:03 Error: Could not load thumbnail for The
Warrior
plexexport-php      | 16:32:04 Analysing media items in section...
plexexport-php      | 16:32:04 Added 26 items from the Movies Korean section
plexexport-php      | 16:32:04 Exporting data for 1 section containing 26
items
plexexport-php      | 16:32:04 Generating and minifying JSON output, this
may take some time...
plexexport-php      | 16:32:04 Wrote 29589 bytes to /app/plex-data/data.js
plexexport-php      | 16:32:04 Plex Export completed in 53.57 seconds
plexexport-php      |
plexexport-php      | ash: /data/index.html: unknown operand
plexexport-php      | Copping app-files to /data
plexexport-php      | Chmoding /data
plexexport-php      |
plexexport-php      | Sleep until next run in 60m

**Comment by ex0nuss** [comment]
This is interesting. 
Please try **connecting to your Plex-Server via the private IP address** of it (**not your domain name**).

I described it in my first message (**Fourth step**):
> Since you try accessing your Plex-server via a public domain, please also try also accessing it via your private IP address if possible.
> Note: Keep in mind choosing the right port when using private IP addresses!
> This is how I personally access  my Plex-server:
> ```
> environment:
>   - PLEX_URL=http://192.168.1.100:32400
> ```

**Comment by ex0nuss** [comment]
Please keep in mind changing up the PLEX_URL accordingly:
```
environment:
  - PLEX_URL=http://PRIVATE_IP:PORT
```
The Port can either be the default 32400 or a different one (e.g. 80)

**Comment by ex0nuss** [comment]
Closed due to inactivity. Feel free to open this issue again. Otherwise I will assume that the problem has been solved.
