### ISSUE TITLE
Any idea how to deploy this on heroku?

### ISSUE THREAD

**Issue by bnichs5** [ex0nuss/Plex-Export-Docker#2]
Any idea how to deploy this on heroku?

**Comment by ex0nuss** [comment]
Though question: 
I don't use Heroku by myself but I heard that you can deploy Docker containers with it.
For it to work you need two containers (PHP and Nginx) which need to share the /data-Directory. I thought about making a single container version tho :)

**Comment by bnichs5** [comment]
Thanks for the quick response.
